name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  fmt:
    name: Formatting
    runs-on: k8s-infrastructure-native
    container:
      image: rust:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: k8s-infrastructure-native
    container:
      image: rust:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - name: Run clippy
        run: cargo make clippy

  tests:
    name: Tests
    runs-on: k8s-infrastructure-native
    container:
      image: rust:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Libudev
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libudev-dev
          version: 1.0
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make
      - name: Run tests
        run: cargo make tests
